#!/bin/bash

if [ -f /opt/custom_run ]; then
    chmod u+x /opt/custom_run
    echo "=>executing /opt/custom_run"
    /opt/custom_run
fi

/opt/create_ticket.py --icinga-hostname ${ICINGA2_MASTER_HOST} --username ${ICINGA2_API_USERNAME} --password ${ICINGA2_API_PASSWORD}

/opt/setup/icinga2

service icinga2 start

trap "service icinga2 stop" HUP INT QUIT ABRT KILL ALRM TERM TSTP

tail -F /var/log/icinga2/icinga2.log &

while pidof icinga2 &>/dev/null; do sleep 5; done