#!/bin/bash

ICINGA2_MASTER_HOST=${ICINGA2_MASTER_HOST:-icinga}
ICINGA2_MASTER_FQDN=${ICINGA2_MASTER_FQDN:-${ICINGA2_MASTER_HOST}}
ICINGA2_MASTER_PORT=${ICINGA2_MASTER_PORT:-5665}
ICINGA2_API_USERNAME=${ICINGA2_API_USERNAME:-root}
ICINGA2_API_PASSWORD=${ICINGA2_API_PASSWORD:-root}
ICINGA2_CLIENT_FQDN=${ICINGA2_CLIENT_FQDN:-$(hostname --fqdn)}


mkdir -p /var/lib/icinga2/api/zones
mkdir -p /var/lib/icinga2/api/log
mkdir -p /var/lib/icinga2/api/repository
chown -R icinga:icinga /var/lib/icinga2
chown -R icinga:icinga /var/spool/icinga2
chown -R icinga:icinga /var/cache/icinga2
chown -R icinga:icinga /var/log/icinga2
chown -R icinga:icinga /etc/icinga2

# enable necessary features
icinga2 feature enable api livestatus command

if [[ ! -f /var/lib/icinga2/certs/$(hostname).crt ]]
then
    /opt/setup/register_icinga_client.py --icinga-hostname ${ICINGA2_MASTER_HOST} --username ${ICINGA2_API_USERNAME} --password ${ICINGA2_API_PASSWORD}
fi

icinga2 daemon -d

tail -F /var/log/icinga2/* &

while pidof icinga2 &>/dev/null; do sleep 5; done