version: '2'
services:
  icinga2:
    image: bebehei/icinga2-client
    restart: on-failure:5
    #Set the correct hostname for the image.
    hostname: icinga2
    privileged: true
    network_mode: host
    environment:
      - ICINGA2_MASTER_HOST=mon
      # If your master's FQDN does not match the hostname, define the name additionally.
      #- ICINGA2_MASTER_FQDN=mon
    volumes:
      - ./cache:/var/cache/icinga2
      - ./etc:/etc/icinga2
      - ./lib:/var/lib/icinga2
      - ./log:/var/log/icinga2
      - ./spool:/var/spool/icinga2
