version: '2.4'
services:
  icinga-client:
    image: adamdelman/icinga-client
    container_name: icinga-client
    restart: on-failure
    #Set the correct hostname for the Icinga client.
    hostname: changeme
    privileged: true
    network_mode: host
    environment:
      - ICINGA2_MASTER_HOST=icinga
      - ICINGA2_API_USERNAME=intsights
      - ICINGA2_API_PASSWORD=Password1!
      # If your Icinga master node's FQDN does not match its hostname, define it additionally.
      #- ICINGA2_MASTER_FQDN=icinga-host
    volumes:
      - ./cache:/var/cache/icinga2
      - ./etc:/etc/icinga2
      - ./lib:/var/lib/icinga2
      - ./log:/var/log/icinga2
      - ./spool:/var/spool/icinga2
    logging:
        driver: json-file
        options:
            max-size: "10m"
    ports:
        - 5665:5665