#!/bin/bash


ICINGA2_MASTER_HOST=${ICINGA2_MASTER_HOST:-mon}
ICINGA2_MASTER_FQDN=${ICINGA2_MASTER_FQDN:-$ICINGA2_MASTER_HOST}
ICINGA2_MASTER_PORT=${ICINGA2_MASTER_PORT:-5665}
ICINGA2_API_USERNAME=${ICINGA2_MASTER_PORT:-root}
ICINGA2_API_PASSWORD=${ICINGA2_MASTER_PORT:-root}
ICINGA2_CLIENT_FQDN=${ICINGA2_CLIENT_FQDN:-$(hostname --fqdn)}

if [ ! "$(ls -A /etc/icinga2)" ]; then
  echo "=> Copying fresh config-files for /etc/icinga2"
  cp -R /etc/icinga2.dist/* /etc/icinga2/
fi

# chown directories and files that might be coming from volumes
mkdir -p /var/log/icinga2/compat/archives
chown -R nagios:adm /var/log/icinga2

mkdir -p /var/lib/icinga2/api/zones
mkdir -p /var/lib/icinga2/api/log
mkdir -p /var/lib/icinga2/api/repository
chown -R nagios:nagios /var/lib/icinga2
chown -R nagios:nagios /var/spool/icinga2
chown -R nagios:nagios /var/cache/icinga2

chown -R nagios:root /etc/icinga2

# enable neccessary features
icinga2 feature enable api livestatus compatlog command

/opt/create_ticket.py --icinga-hostname ${ICINGA2_MASTER_HOST} --username ${ICINGA2_API_USERNAME} --password ${ICINGA2_API_PASSWORD}