#!/usr/bin/env bash
# this script sets up unattended aur access via trizen for a user given as the first argument
set -o pipefail -e

[[ -z "$1" ]] && echo "You must specify a user name" && exit 1
AUR_USER=$1

# create the user
useradd -m ${AUR_USER}

# set the user's password to blank
echo "${AUR_USER}:" | chpasswd -e

# install devel packages (without systemd
pkgs=$(pacman -S base-devel --print-format '%n ');pkgs=${pkgs//systemd/};pkgs=${pkgs//$'\n'/}
pacman -S --needed --noprogressbar --noconfirm $pkgs vi

# give the aur user passwordless sudo powers
echo "${AUR_USER}      ALL = NOPASSWD: ALL" >> /etc/sudoers

# use all possible cores for subsequent package builds
sed -i 's,#MAKEFLAGS="-j2",MAKEFLAGS="-j$(nproc)",g' /etc/makepkg.conf

# don't compress the packages built here
sed -i "s,PKGEXT='.pkg.tar.xz',PKGEXT='.pkg.tar',g" /etc/makepkg.conf

# install trizen
wget https://aur.archlinux.org/cgit/aur.git/snapshot/trizen.tar.gz -O /tmp/trizen.tar.gz
cd /tmp
tar xvf trizen.tar.gz
cd trizen
chown ${AUR_USER}:${AUR_USER} /tmp/trizen
sudo -u ${AUR_USER} makepkg -Cifs --noconfirm

# do a trizen system update
su ${AUR_USER} -c 'trizen -Syyua --noprogressbar --noedit --noconfirm'

echo "Packages from the AUR can now be installed like this:"
echo "su ${AUR_USER} -c 'trizen -S --needed --noprogressbar --noedit --noconfirm PACKAGE'"